import { AudioProfile, EQBand } from '../types';

const flatEQ = (): EQBand[] => [
  { id: 'b1', frequency: 125,  gain: 0, label: '125Hz' },
  { id: 'b2', frequency: 500,  gain: 0, label: '500Hz' },
  { id: 'b3', frequency: 1000, gain: 0, label: '1kHz'  },
  { id: 'b4', frequency: 3000, gain: 0, label: '3kHz'  },
  { id: 'b5', frequency: 8000, gain: 0, label: '8kHz'  },
];

const voiceEQ = (): EQBand[] => [
  { id: 'b1', frequency: 125,  gain: -4, label: '125Hz' },
  { id: 'b2', frequency: 500,  gain: -2, label: '500Hz' },
  { id: 'b3', frequency: 1000, gain:  4, label: '1kHz'  },
  { id: 'b4', frequency: 3000, gain:  6, label: '3kHz'  },
  { id: 'b5', frequency: 8000, gain:  2, label: '8kHz'  },
];

const channelFlat = (vol = 1) => ({ bands: flatEQ(), volume: vol });
const channelVoice = (vol = 1) => ({ bands: voiceEQ(), volume: vol });

export const PRESET_PROFILES: AudioProfile[] = [
  {
    id: 'home',
    name: 'Casa',
    icon: '🏠',
    leftEQ:  { bands: [
      { id: 'b1', frequency: 125,  gain: -2, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  0, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  3, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  4, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  1, label: '8kHz'  },
    ], volume: 0.8 },
    rightEQ: { bands: [
      { id: 'b1', frequency: 125,  gain: -2, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  0, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  3, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  4, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  1, label: '8kHz'  },
    ], volume: 0.8 },
    stereoBalance: 0,
    amplification: 2,
    sonikaClean: true,
    conversationMode: false,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bluetooth_headphones',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'restaurant',
    name: 'Ristorante',
    icon: '🍽️',
    leftEQ:  { bands: [
      { id: 'b1', frequency: 125,  gain: -8, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain: -4, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  6, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  8, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  3, label: '8kHz'  },
    ], volume: 0.9 },
    rightEQ: { bands: [
      { id: 'b1', frequency: 125,  gain: -8, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain: -4, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  6, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  8, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  3, label: '8kHz'  },
    ], volume: 0.9 },
    stereoBalance: 0,
    amplification: 3,
    sonikaClean: true,
    conversationMode: true,
    preferredMicSource: 'bluetooth',
    preferredOutput: 'bluetooth_headphones',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'street',
    name: 'Strada',
    icon: '🚶',
    leftEQ:  { bands: [
      { id: 'b1', frequency: 125,  gain:  0, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain: -1, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  2, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  3, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  2, label: '8kHz'  },
    ], volume: 0.7 },
    rightEQ: { bands: [
      { id: 'b1', frequency: 125,  gain:  0, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain: -1, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  2, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  3, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  2, label: '8kHz'  },
    ], volume: 0.7 },
    stereoBalance: 0,
    amplification: 2,
    sonikaClean: false,
    conversationMode: false,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bone_conduction',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'music',
    name: 'Musica',
    icon: '🎵',
    leftEQ:  { bands: [
      { id: 'b1', frequency: 125,  gain:  3, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  1, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  0, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  1, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  3, label: '8kHz'  },
    ], volume: 0.85 },
    rightEQ: { bands: [
      { id: 'b1', frequency: 125,  gain:  3, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  1, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:  0, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:  1, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  3, label: '8kHz'  },
    ], volume: 0.85 },
    stereoBalance: 0,
    amplification: 1,
    sonikaClean: false,
    conversationMode: false,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bluetooth_headphones',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'medical',
    name: 'Visita Medica',
    icon: '🏥',
    leftEQ:  channelVoice(1),
    rightEQ: channelVoice(1),
    stereoBalance: 0,
    amplification: 5,
    sonikaClean: true,
    conversationMode: true,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bluetooth_headphones',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'night',
    name: 'Notte',
    icon: '🌙',
    leftEQ:  { bands: [
      { id: 'b1', frequency: 125,  gain: -10, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  -6, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:   2, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:   8, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  10, label: '8kHz'  },
    ], volume: 0.3 },
    rightEQ: { bands: [
      { id: 'b1', frequency: 125,  gain: -10, label: '125Hz' },
      { id: 'b2', frequency: 500,  gain:  -6, label: '500Hz' },
      { id: 'b3', frequency: 1000, gain:   2, label: '1kHz'  },
      { id: 'b4', frequency: 3000, gain:   8, label: '3kHz'  },
      { id: 'b5', frequency: 8000, gain:  10, label: '8kHz'  },
    ], volume: 0.3 },
    stereoBalance: 0,
    amplification: 1,
    sonikaClean: false,
    conversationMode: false,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bluetooth_headphones',
    isPreset: true,
    createdAt: 0,
  },
  {
    id: 'custom',
    name: 'Personalizzato',
    icon: '⚙️',
    leftEQ:  channelFlat(0.8),
    rightEQ: channelFlat(0.8),
    stereoBalance: 0,
    amplification: 1,
    sonikaClean: false,
    conversationMode: false,
    preferredMicSource: 'smartphone',
    preferredOutput: 'bluetooth_headphones',
    isPreset: false,
    createdAt: 0,
  },
];
